repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.3.0
    hooks:
      - id: reorder-python-imports
        args:
          - --py37-plus
          - --add-import
          - from __future__ import annotations

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.34.0
    hooks:
      - id: pyupgrade
        args:
          - "--py37-plus"

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.2.3
    hooks:
      - id: add-trailing-comma

  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8

  - repo: https://github.com/fsouza/autoflake8
    rev: v0.3.2
    hooks:
      - id: autoflake8

  - repo: local
    hooks:
      - id: fix-version
        name: ensure version consistency in docs, code and distribution
        language: python
        entry: scripts/fix_version.py
        pass_filenames: false
