name: Build
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
        os:
          - macos
          - ubuntu
          - windows

    name: tests
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v3.0.0

      - uses: actions/setup-python@v3.1.0
        with:
          python-version: ${{ matrix.python-version }}

      - run: pip install poetry

      - name: install deps
        run: poetry install

      - name: run tests
        run: poetry run pytest

  lint:
    name: pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0

      - uses: actions/setup-python@v3.1.0
        with:
          python-version: 3.x

      - name: install pre-commit
        run: pip install pre-commit

      - name: pre-commit cache
        uses: actions/cache@v3.0.1
        with:
          path: ~/.cache/pre-commit
          key: "${{ hashFiles('.pre-commit-config.yaml') }}"

      - run: pre-commit run --all-files --show-diff-on-failure

  fuzz:
    strategy:
      matrix:
        options:
          - ""
          - "--expand-star-imports"
          - "--remove-duplicate-keys"
          - "--remove-unused-variables"
          - "--remove-duplicate-keys --remove-unused-variables"
          - "--expand-star-imports --remove-duplicate-keys"
          - "--expand-star-imports --remove-duplicate-keys --remove-unused-variables"

    name: fuzz (${{ matrix.options }})
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0

      - uses: actions/setup-python@v3.1.0
        with:
          python-version: "3.10"

      - run: pip install poetry

      - run: poetry install

      - name: run fuzz
        run: ./scripts/fuzz.sh ${{ matrix.options }}
