name: Publish
on: create

jobs:
  release:
    if: github.event.ref_type == 'tag'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0

      - uses: actions/setup-python@v2.3.2
        with:
          python-version: 3.x

      - run: pip install poetry pre-commit

      - run: poetry install

      - run: poetry run pytest

      - name: pre-commit cache
        uses: actions/cache@v2.1.7
        with:
          path: ~/.cache/pre-commit
          key: "${{ hashFiles('.pre-commit-config.yaml') }}"

      - run: pre-commit run --all-files --show-diff-on-failure

      - run: poetry build

      - run: poetry publish
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
